name: "Create artifact"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  producer:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean compile -DskipTests

      - name: Package artifact
        run: mvn package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: users-artifact
          path: target/*.jar
